development:
  adapter: postgresql
  encoding: utf8
  database: star_wars_dating_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: star_wars_dating_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: star_wars_dating_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
